@startuml
OktaLogger *-- OktaLoggerDestinationBase : contains
OktaLoggerDestinationBase .. OktaLogLevel

class OktaLogger {
  var main: OktaLogger? static instance
  let destinations: [string:OktaLoggerDestinationProtocol]
  init(destinations: [OktaLoggerDestinationProtocol])
  log(level:eventName:message:properties:file:line:function)

  debug(eventName:message:properties)
  info(eventName:message:properties)
  warning(eventName:message:properties)
  uiEvent(eventName:message:properties)
  error(eventName:message:properties)
}

class OktaLoggerDestinationBase {
  let identifier: String
  var logLevel: OktaLogLevel
  log(level:eventName:message:properties:file:line:function)
}

class OktaLogLevel {
  static let off
  static let debug
  static let info
  static let warning
  static let uiEvent
  static let error
  static let all
}
@enduml