@startuml OktaLoggerSequence
participant "Application\n(OV + OM)" as app
participant OktaLogger as logger
participant "ConsoleDestination\n(level: .all)" as console
participant "FileDestination\n(level: .info, .error)" as file
participant "FirebaseDestination\n(level: error)" as firebase

app->app: Create destinations\n(console, file, firebase)
app->logger: Create OktaLogger instance\nwith destinations
app->logger: logError(event, message, data)
logger->console:logError()
console->console: Log to console + IDE
logger->file: logError()
file->file: Write log entry to file
logger->firebase: logError()
firebase->firebase: recordNonFatal(error)

app->logger: logDebug("network request")
logger->console: log to console + IDE
logger->logger: Skip destinations\nwithout level: .debug

@enduml